from __future__ import annotations

import html as html_mod
import logging
import smtplib
import ssl
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional

from article_tracker.config.config_schema import EmailConfig
from article_tracker.models.article import Article

logger = logging.getLogger(__name__)

_CSS = """
.container{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;color:#0f172a}
.card{border:1px solid #e5e7eb;border-radius:16px;padding:16px 18px;margin:14px 0;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.04)}
.title{font-weight:700;font-size:18px;margin:0 0 6px 0}
.meta-line{color:#667085;font-size:13px;margin:2px 0}
.links a{color:#2563eb;text-decoration:none;margin-right:12px}
.links a:hover{text-decoration:underline}
.section{border:1px solid #eef2f7;border-radius:10px;padding:8px 10px;background:#f8fafc;margin-top:8px}
.section h4{margin:4px 0 6px 0;font-size:14px}
.tier-badge{font-size:11px;font-weight:700;padding:2px 8px;border-radius:999px;margin-left:6px}
.tier-core{background:#dbeafe;color:#1d4ed8}
.tier-proxy{background:#fef3c7;color:#92400e}
.tier-eco{background:#d1fae5;color:#065f46}
.tier-noise{background:#f3f4f6;color:#6b7280}
.hr{height:1px;background:#e5e7eb;margin:14px 0}
.footer{color:#667085;font-size:13px;margin:20px 0 10px}
"""

_TIER_CLS = {"core": "tier-core", "proxy": "tier-proxy", "eco": "tier-eco", "noise": "tier-noise"}


def _esc(x: Optional[str]) -> str:
    return html_mod.escape(x or "", quote=True)


def _card(a: Article) -> str:
    tier = a.screening_tier.value if a.screening_tier else ""
    tier_html = f'<span class="tier-badge {_TIER_CLS.get(tier, "")}">{tier.upper()}</span>' if tier else ""

    parts = [f'<div class="card"><div class="title">{_esc(a.title)}{tier_html}</div>']

    if a.authors:
        parts.append(f'<div class="meta-line">Authors: {_esc(", ".join(a.authors[:5]))}{"..." if len(a.authors) > 5 else ""}</div>')
    if a.venue:
        parts.append(f'<div class="meta-line">Venue: {_esc(a.venue)}</div>')
    if a.published:
        parts.append(f'<div class="meta-line">Published: {a.published[:10]}</div>')

    links = []
    if a.html_url:
        links.append(f'<a href="{_esc(a.html_url)}">Abs</a>')
    if a.pdf_url:
        links.append(f'<a href="{_esc(a.pdf_url)}">PDF</a>')
    for i, u in enumerate(a.code_links[:3]):
        links.append(f'<a href="{_esc(u)}">Code{i+1}</a>')
    if links:
        parts.append(f'<div class="links" style="margin-top:8px">{" · ".join(links)}</div>')

    if a.abstract:
        parts.append(f'<div class="section"><h4>Abstract</h4><div style="white-space:pre-wrap">{_esc(a.abstract)}</div></div>')

    if a.digest_en or a.digest_zh:
        inner = ""
        if a.digest_en:
            inner += f'<div style="white-space:pre-wrap">{_esc(a.digest_en)}</div>'
        if a.digest_zh:
            inner += f'<div style="white-space:pre-wrap;margin-top:8px">{_esc(a.digest_zh)}</div>'
        parts.append(f'<div class="section"><h4>Summary / 总结</h4>{inner}</div>')

    if a.title_zh:
        parts.append(f'<div class="section"><h4>中文标题</h4><div style="white-space:pre-wrap">{_esc(a.title_zh)}</div></div>')

    parts.append('</div>')
    return "\n".join(parts)


def send_email(articles: List[Article], config: EmailConfig, subject_prefix: str = "Paper Tracker") -> str | None:
    if not config.enabled:
        return None

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    tier_counts = {"core": 0, "proxy": 0, "eco": 0}
    for a in articles:
        if a.screening_tier and a.screening_tier.value in tier_counts:
            tier_counts[a.screening_tier.value] += 1
    stats_text = f"Core {tier_counts['core']} · Proxy {tier_counts['proxy']} · Eco {tier_counts['eco']}"

    cards = "\n".join(_card(a) for a in articles[:50])
    html_body = f"""<meta charset="utf-8">
<div class="container">
<h2 style="margin:8px 0 12px 0;">{_esc(subject_prefix)}</h2>
<style>{_CSS}</style>
<div style="font-size:12px;color:#667085;margin-bottom:12px;">{now_str} · {stats_text}</div>
<div class="hr"></div>
{cards}
<div class="footer">Generated by article_tracker</div>
</div>"""

    msg = MIMEMultipart()
    msg["From"] = config.sender
    msg["To"] = ", ".join(config.to)
    msg["Subject"] = f"{subject_prefix} — {now_str}"
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        if config.tls_mode == "ssl" or (config.tls_mode == "auto" and config.smtp_port == 465):
            ctx = ssl.create_default_context()
            with smtplib.SMTP_SSL(config.smtp_server, config.smtp_port, context=ctx, timeout=20) as s:
                s.login(config.smtp_user, config.smtp_pass)
                s.sendmail(msg["From"], config.to, msg.as_string())
        else:
            ctx = ssl.create_default_context()
            with smtplib.SMTP(config.smtp_server, config.smtp_port, timeout=20) as s:
                s.ehlo()
                s.starttls(context=ctx)
                s.ehlo()
                s.login(config.smtp_user, config.smtp_pass)
                s.sendmail(msg["From"], config.to, msg.as_string())
        return "sent"
    except Exception as e:
        logger.warning(f"Email send failed: {e}")
        return f"failed: {e}"
